Пришёл, увидел, загрузил (часть 1)
htmlacademy-ecmascript/977737-big-trip-13 pull request #11
Opened 2020-12-26 14:47 UTC by Pavelliss

2020-12-26 14:50 UTC, Pavelliss commented
Мне кажется я перемудрил с обновлением данных при клике на конкретный offer. Оказалось проще переписать логику обновления данных (offer), но мне не оч нравится моё решение хотя бы сточки зрения оптимизации. 
Обрати на это внимание, хочу знать твоё мнение, как это сделать лучше.

2020-12-28 09:43 UTC, ant1quar requested changes

2020-12-28 09:43 UTC, ant1quar commented on src/view/form-edit.js
> +  if (photos === []) {
тут всегда false, даже `[] !== []` нужно проверять `photos.length`

2020-12-28 09:43 UTC, ant1quar commented on src/utils/util.js
> +  });
А ты знаешь reduce и map? Через них будет красивее, но это необязательное задание

2020-12-28 09:43 UTC, ant1quar commented on src/view/trip-event.js
> +      ${offers.length === 0 ? `` : createAddtionalOptions(offers)}
Нужно обновить этот кусок - делать slice(0,2) стоит на уровне генерации данных, а рисовать в компоненте столько офферов, сколько передали извне.

2021-01-06 17:47 UTC, merged